version: 0.0
Resources:
    ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ServerlessRestApi
      Description: !Sub "RestApi deployment Version: ${ApiVersion}"
      StageName: !Ref EnvironmentName