# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

phases:

  build:
    commands:
      - dotnet restore Poc-LR/Poc-LR.csproj
      - dotnet build Poc-LR/Poc-LR.csproj
      - dotnet publish Poc-LR/Poc-LR.csproj -o ./main      
artifacts:
  files:
    - '**/*'
  base-directory: 'develop'